version: '3'
services:
    namenode:
        image: "krokodilchk/dfs-namenode"
        depends_on:
            - storage01
            - storage02
            - storage03
        ports:
            - "4000:4000"
    storage01:
        image: "krokodilchk/dfs-storage"
        ports:
            - "3000:4000"
    storage02:
        image: "krokodilchk/dfs-storage"
        ports:
            - "3040:4000"
    storage03:
        image: "krokodilchk/dfs-storage"
        ports:
            - "3080:4000"
